name: CI and dev

on: 
  push:
    branches: 
      - main 

  pull_request:
    branches: 
      - main 

jobs:
  build:
    runs-on: [windows-latest]
    
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup msbuild
        uses: microsoft/setup-msbuild@v1

      - name: Setup NuGet
        uses: NuGet/setup-msbuild@v1.0.2
        
      - name: Restore Nuget packages
        run: nuget restore OnlineCourse.snl

      - name: Build solution
        run: msbuild OnlineCourse.snl

       
